In [2]:
from string import punctuation, digits
import numpy as np
import random
import utils
import pandas as pd

In [3]:
def get_order(n_samples):
    try:
        with open(str(n_samples) + '.txt') as fp:
            line = fp.readline()
            return list(map(int, line.split(',')))
    except FileNotFoundError:
        random.seed(1)
        indices = list(range(n_samples))
        random.shuffle(indices)
        return indices

# Hinge Loss

In [4]:
x = np.array([[1, 2], [1, 2]])
label, theta, theta_0 = np.array([1, 1]), np.array([-1, 1]), -0.2
exp_res = 1 - 0.8

In [5]:
len(x[0])

2

In [6]:
def hinge_loss_single(feature_vector, label, theta, theta_0):
    """
    Finds the hinge loss on a single data point given specific classification
    parameters.

    Args:
        feature_vector - A numpy array describing the given data point.
        label - A real valued   number, the correct classification of the data
            point.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given data point and parameters.
    """
    # Your code here
    z = label*(np.dot(theta, feature_vector)+theta_0)
    if z>=1:
        return 0
    else:
        return 1-z

In [7]:
def hinge_loss_full(feature_matrix, labels, theta, theta_0):
    """
    Finds the total hinge loss on a set of data given specific classification
    parameters.

    Args:
        feature_matrix - A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given dataset and parameters. This number should be the average hinge
    loss across all of the points in the feature matrix.
    """
    hsum = np.zeros((feature_matrix.shape[0],1))
    # Your code here
    for i in range(feature_matrix.shape[0]):
            hsum[i] = hinge_loss_single(feature_matrix[i,:], labels[i], theta, theta_0)
    return np.sum(hsum)/len(feature_matrix[0])
    #raise NotImplementedError

In [8]:
x = np.array([[1, 2], [1, 2]])
label, theta, theta_0 = np.array([1, 1]), np.array([-1, 1]), -0.2
exp_res = 1 - 0.8

In [9]:
hinge_loss_full(x,label, theta, theta_0) == exp_res

True

In [10]:
def hinge_loss_full(feature_matrix, labels, theta, theta_0):
    """
    Finds the total hinge loss on a set of data given specific classification
    parameters.

    Args:
        feature_matrix - A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.


    Returns: A real number representing the hinge loss associated with the
    given dataset and parameters. This number should be the average hinge
    loss across all of the points in the feature matrix.
    """
    hinge_full = 1 - (labels*(np.dot(feature_matrix, theta)+theta_0))
    #hinge_full = np.where(hinge_full==0,1,hinge_full)
    hinge_full[hinge_full<0]=0
    
    return hinge_full.mean()

In [11]:
hinge_loss_full(x,label, theta, theta_0) == exp_res

True

In [12]:
print ("Hello :  %d     Sce : %s" %(1, 0)) 

Hello :  1     Sce : 0


In [13]:
for i,j in zip(x,range(np.size(x,0))):
    print((i,j))

(array([1, 2]), 0)
(array([1, 2]), 1)


# Perceptron

In [14]:
def perceptron_single_step_update(
        feature_vector,
        label,
        current_theta,
        current_theta_0):
    """
    Properly updates the classification parameter, theta and theta_0, on a
    single step of the perceptron algorithm.

    Args:
        feature_vector - A numpy array describing a single data point.
        label - The correct classification of the feature vector.
        current_theta - The current theta being used by the perceptron
            algorithm before this update.
        current_theta_0 - The current theta_0 being used by the perceptron
            algorithm before this update.

    Returns: A tuple where the first element is a numpy array with the value of
    theta after the current update has completed and the second element is a
    real valued number with the value of theta_0 after the current updated has
    completed.
    """
    # Your code here
    if (label * (np.dot(current_theta, feature_vector) + current_theta_0)) <= 0:
        current_theta += label*feature_vector
        current_theta_0 += label

    return (current_theta, current_theta_0)

In [15]:
x = np.array([-0.40693195 , 0.48264844, -0.38956493, -0.47310565, -0.43401042,  0.36199333,
  0.44056266, -0.29557264, -0.08417648,  0.27143027])
y = -1
theta = np.array([-0.351117,   -0.17636743,  0.01502589,  0.27085476 , 0.42011513,  0.20540997,
 -0.07781607 , 0.03085709 , 0.08954577 , 0.1959461 ])
theta_0 = -0.4499382570373128

In [16]:
y * (np.dot(theta,x)+theta_0)

0.6319100897740646

In [17]:
if (y * (np.dot(theta,x)+theta_0))<= 0:
    theta += y*x
    theta_0 += y
theta, theta_0

(array([-0.351117  , -0.17636743,  0.01502589,  0.27085476,  0.42011513,
         0.20540997, -0.07781607,  0.03085709,  0.08954577,  0.1959461 ]),
 -0.4499382570373128)

In [18]:
perceptron_single_step_update(x,y,theta,theta_0)

(array([-0.351117  , -0.17636743,  0.01502589,  0.27085476,  0.42011513,
         0.20540997, -0.07781607,  0.03085709,  0.08954577,  0.1959461 ]),
 -0.4499382570373128)

In [19]:
x.shape

(10,)

In [20]:
theta, theta_0 = np.zeros((x.shape[0],)),0
#theta_0 = 0
theta, theta_0 = perceptron_single_step_update(x,y,theta,theta_0)[0], perceptron_single_step_update(x,y,theta,theta_0)[1]
theta, theta_0

(array([ 0.40693195, -0.48264844,  0.38956493,  0.47310565,  0.43401042,
        -0.36199333, -0.44056266,  0.29557264,  0.08417648, -0.27143027]),
 0)

In [21]:
def perceptron(feature_matrix, labels, T):
    """
    Runs the full perceptron algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    NOTE: Iterate the data matrix by the orders returned by get_order(feature_matrix.shape[0])

    Args:
        feature_matrix -  A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the perceptron algorithm
            should iterate through the feature matrix.

    Returns: A tuple where the first element is a numpy array with the value of
    theta, the linear classification parameter, after T iterations through the
    feature matrix and the second element is a real number with the value of
    theta_0, the offset classification parameter, after T iterations through
    the feature matrix.
    """
    theta, theta_0 = np.zeros((feature_matrix.shape[1],)), 0
    print(feature_matrix.shape[0])
    # Your code here
    for t in range(T):
        for i in range(feature_matrix.shape[0]):
            # Your code here
            t = perceptron_single_step_update(feature_matrix[i, :], labels[i], theta, theta_0)
            theta, theta_0 = t[0], t[1]
            
            
            #pass
    
    return(theta, theta_0)

In [22]:
i=0
theta, theta_0 = np.zeros((feature_matrix.shape[1],)), 0
feature_matrix = np.array([[1, 2]])
labels = np.array([1])
T = 1
perceptron(feature_matrix, labels, T)
#perceptron_single_step_update(feature_matrix[i, :], labels[i], theta, theta_0), feature_matrix.shape[0]

NameError: name 'feature_matrix' is not defined

In [23]:
feature_matrix.shape[0]

NameError: name 'feature_matrix' is not defined

In [24]:
for i in range(1):
    print(i)

0


In [25]:
feature_matrix = np.array([[ 0.09334818 ,-0.01544469 , 0.13405622 , 0.34491817 , 0.04166459,  0.39493563,
  -0.18338607, -0.43957034, -0.46190975, -0.24975976]
 [ 0.41657729 , 0.07569962,  0.41251052, -0.36185631, -0.12757683 , 0.06123831,
   0.20650185 , 0.26003101, 0.069105  , -0.26563641]
 [-0.19188315,  0.21033365, -0.23713144, -0.08926778,  0.26603686 , 0.47717252,
  -0.47867535, -0.24245049 , 0.36502655, -0.24305283]
 [-0.17016906, -0.28178701, -0.48180109,  0.13899522, -0.19500262, -0.18908814,
   0.25368259, -0.0316778 ,  0.10088184, -0.18054423]
 [-0.27601958 ,-0.39640354, -0.25004556,  0.180031,   -0.1974046,  -0.08591306,
  -0.1753684,  -0.12180758,  0.34427095, -0.40503603]])
labels = np.array([-1  1  1  1 -1])
T = 5
perceptron(feature_matrix, labels, T)

SyntaxError: invalid syntax (<ipython-input-25-b0cfc6850fc3>, line 11)

In [26]:
def average_perceptron(feature_matrix, labels, T):
    """
    Runs the average perceptron algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    NOTE: Iterate the data matrix by the orders returned by get_order(feature_matrix.shape[0])


    Args:
        feature_matrix -  A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the perceptron algorithm
            should iterate through the feature matrix.

    Returns: A tuple where the first element is a numpy array with the value of
    the average theta, the linear classification parameter, found after T
    iterations through the feature matrix and the second element is a real
    number with the value of the average theta_0, the offset classification
    parameter, found after T iterations through the feature matrix.

    Hint: It is difficult to keep a running average; however, it is simple to
    find a sum and divide.
    """
    theta, theta_0 = np.zeros((feature_matrix.shape[1],)), 0
    sum_thetas = np.zeros(feature_matrix.shape[1],)
    sum_thetas_0 = 0
    n = feature_matrix.shape[0]
    # Your code here
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
            # Your code here

            t = perceptron_single_step_update(feature_matrix[i, :], labels[i], theta, theta_0)
            theta, theta_0 = t[0], t[1]

            sum_thetas += theta
            sum_thetas_0 += theta_0
            # pass
    theta_avg = sum_thetas/(n*T)
    theta_0_avg = sum_thetas_0/(n*T)
    return (theta_avg, theta_0_avg)

In [27]:
feature_matrix = np.array([[1, 2]])
labels = np.array([1])
T = 1
average_perceptron(feature_matrix, labels, T)

(array([1., 2.]), 1.0)

In [28]:
def average_perceptron2(feature_matrix, labels, T):
    theta = np.zeros(feature_matrix.shape[1], )
    theta_0 = 0
    
    theta_aggregate = np.zeros(feature_matrix.shape[1], )
    theta_0_aggregate = 0
    
    for t in range(T):
        for i in get_order(feature_matrix.shape[0]):
            theta, theta_0 = perceptron_single_step_update(feature_matrix[i], labels[i], theta, theta_0)
            theta_aggregate += theta
            theta_0_aggregate += theta_0
            
    return theta_aggregate / (feature_matrix.shape[0] * T), theta_0_aggregate / (feature_matrix.shape[0] * T)

In [29]:
feature_matrix = np.array([[1, 2]])
labels = np.array([1])
T = 1
average_perceptron2(feature_matrix, labels, T)

(array([1., 2.]), 1.0)

# Pegasos algorithm

In [30]:
def pegasos_single_step_update(
        feature_vector,
        label,
        L,
        eta,
        current_theta,
        current_theta_0):
    """
    Properly updates the classification parameter, theta and theta_0, on a
    single step of the Pegasos algorithm

    Args:
        feature_vector - A numpy array describing a single data point.
        label - The correct classification of the feature vector.
        L - The lamba value being used to update the parameters.
        eta - Learning rate to update parameters.
        current_theta - The current theta being used by the Pegasos
            algorithm before this update.
        current_theta_0 - The current theta_0 being used by the
            Pegasos algorithm before this update.

    Returns: A tuple where the first element is a numpy array with the value of
    theta after the current update has completed and the second element is a
    real valued number with the value of theta_0 after the current updated has
    completed.
    """
    # Your code here
    k = 1-L*eta

    if (label * (np.dot(current_theta, feature_vector) + current_theta_0)) <= 1:
        current_theta = current_theta*k + eta*label * feature_vector
        current_theta_0 = current_theta_0 + eta*label
        print(1)

    else:
        current_theta = current_theta * k
        #current_theta_0 *=k
    return (current_theta, current_theta_0)

In [31]:
feature_vector = np.array([1, 2])
label, theta, theta_0 = 1, np.array([-1, 1]), -1.5
L = 0.2
eta = 0.1

pegasos_single_step_update(
        feature_vector,
        label,
        L,
        eta,
        theta,
        theta_0)

1


(array([-0.88,  1.18]), -1.4)

In [32]:
feature_vector = np.array([-0.09525004, -0.46044561,  0.39957794, -0.13994223, -0.16127799, -0.24583467,
  0.30520314, -0.43346013,  0.10093966, -0.43394943])
label= -1
L= 0.8226983197289679
eta= 0.9455762122880957
theta= np.array([-0.03873073,  0.35948524, -0.14898855, -0.26189652,  0.0232371,  -0.12458866,
 -0.09012346,  0.06734868,  0.01924999, -0.15494901])
theta_0= -1.40455069784516

#label * (np.dot(theta, feature_vector) + theta_0)
pegasos_single_step_update(feature_vector, label, L, eta, theta, theta_0)[0]

array([-0.00860117,  0.07983306, -0.03308679, -0.05816094,  0.0051604 ,
       -0.02766816, -0.02001426,  0.01495653,  0.00427496, -0.03441046])

In [33]:
def pegasos(feature_matrix, labels, T, L):
    """
    Runs the Pegasos algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    For each update, set learning rate = 1/sqrt(t),
    where t is a counter for the number of updates performed so far (between 1
    and nT inclusive).

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    Args:
        feature_matrix - A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the algorithm
            should iterate through the feature matrix.
        L - The lamba value being used to update the Pegasos
            algorithm parameters.

    Returns: A tuple where the first element is a numpy array with the value of
    the theta, the linear classification parameter, found after T
    iterations through the feature matrix and the second element is a real
    number with the value of the theta_0, the offset classification
    parameter, found after T iterations through the feature matrix.
    """
    # Your code here
    theta, theta_0 = np.zeros((feature_matrix.shape[1],)), 0

    # Your code here
    for t in range(T):
        eta = 1/np.sqrt(t+1)
        for i in get_order(feature_matrix.shape[0]):
            # Your code here

            t = pegasos_single_step_update(feature_matrix[i, :], L, eta, labels[i], theta, theta_0)
            theta, theta_0 = t[0], t[1]
            # pass
    return (theta, theta_0)

In [35]:
get_order(feature_matrix.shape[0])

[0]

# Automatic Review Analyzer

In [42]:
df = pd.read_csv('reviews_train.tsv', sep = '\t')

In [43]:
df

sentiment   productId          userId  \
0            -1  B000EQYQBO  A2JZVE0Y19VLL0   
1            -1  B000LKVHYC  A3NAKOMAS0I5L9   
2            -1  B003QRQRY2   ARBO3XW14MNGA   
3            -1  B008EG58V8  A1IQXGT4MJUYJ8   
4             1  B004WZZY8M  A2TBL6WAZGXB9P   
...         ...         ...             ...   
3995         -1  B0038B1DEU  A3MKRM2Q9F04UH   
3996          1  B0002CDZD0  A1ESH5GWEGT2ZX   
3997          1  B006N3I2SK  A2S0YE8GUSX20A   
3998          1  B004TPUSU4  A16J5HGMGX5LWM   
3999         -1  B001TLY7BM   AKYQ59VS0B38Q   

                                                summary  \
0                                            blue chips   
1                                Bad even for 'healthy'   
2                             Alot of money for one can   
3     The Box says "OATMEAL SQUARES" which I believe...   
4                                            Delicious!   
...                                                 ...   
3995                  Great nutrititious drink for kids   
3996                             SOOO GOOD FOR THE SKIN   
3997     Deep fabulous rich decaf coffee for the Keurig   
3998                  EXCELLENT American-made GF pasta!   
3999                                           cat food   

                                                   text  helpfulY  helpfulN  
0     The chips are okay Not near as flavorful as th...         0         0  
1     I had high hopes for this, but it was bad.  Re...         0         0  
2     I guess it's only one can since there is nothi...         1         1  
3     "Oatmeal Squares" is in about the largest prin...         0         0  
4     I really enjoyed this flavor, this has a very ...         1         0  
...                                                 ...       ...       ...  
3995  I bought both the Berry and Chocolate drinks f...         4         2  
3996  THIS LAVENDER IS SOOO GOOD.IT LOOKS,SMELLS,TAS...         1         0  
3997  Great great decaf.  Made the Keurig worth it. ...         1         0  
3998  Cooks up al-dente with great flavor. Doesn't f...         0         0  
3999  The photo presented by a reviewer convinced me...         2        10  

[4000 rows x 7 columns]

## Classification and Accuracy

In [44]:
def classify(feature_matrix, theta, theta_0):
    """
    A classification function that uses theta and theta_0 to classify a set of
    data points.

    Args:
        feature_matrix - A numpy matrix describing the given data. Each row
            represents a single data point.
                theta - A numpy array describing the linear classifier.
        theta - A numpy array describing the linear classifier.
        theta_0 - A real valued number representing the offset parameter.

    Returns: A numpy array of 1s and -1s where the kth element of the array is
    the predicted classification of the kth row of the feature matrix using the
    given theta and theta_0. If a prediction is GREATER THAN zero, it should
    be considered a positive classification.
    """
    # Your code here
    classification = np.dot(feature_matrix, theta)+theta_0
    classification[classification > 0] = 1
    classification[classification < 0] = -1

    return classification

In [45]:
feature_matrix = np.array([[1, 1], [1, 1], [1, 1]])
theta = np.array([1, 1])
theta_0 = 0

classify(feature_matrix, theta, theta_0)

array([1, 1, 1])

In [46]:
feature_matrix = np.array([[-1, 1]])
theta = np.array([1, 1])
theta_0 = 0
exp_res = np.array([-1])

classify(feature_matrix, theta, theta_0)

array([0])

In [47]:
np.dot(np.array([[-1, 1]]), np.array([1, 1]))

array([0])

In [51]:
def extract_words(input_string):
    """
    Helper function for bag_of_words()
    Inputs a text string
    Returns a list of lowercase words in the string.
    Punctuation and digits are separated out into their own words.
    """
    for c in punctuation + digits:
        input_string = input_string.replace(c, ' ' + c + ' ')

    return input_string.lower().split()


In [58]:
def bag_of_words(texts):
    """
    Inputs a list of string reviews
    Returns a dictionary of unique unigrams occurring over the input

    Feel free to change this code as guided by Problem 9
    """
    # Your code here
    dictionary = {} # maps word to unique index
    for text in texts:
        word_list = extract_words(text)
        #print(word_list)
        for word in word_list:
            if word not in dictionary:
                dictionary[word] = len(dictionary)
    return dictionary

In [59]:
texts = 'Something s Changed with Canidae food I fed and recommended this food for several years as one of the best dry foods available. However, over the last few months (late 2007) something has changed.  My dogs experienced chronic digestive upset on the food and refused to eat it.  Upon switching to another quality food, the problems stopped.  I tried another bag last week-- same results.  Other dog owners/breeders/vets/handlers have also reported problems with Canidae foods over the past few months.  No one, including myself, has been successful in getting any sort of satisfactory reply from Canidae when asked if they had changed formulas, ingredient suppliers, etc. I am disappointed-- Canidae was one of the few quality foods that had not raised prices significantly over the past year and was still affordable for most dog owners.  Apparently that has also led to changes that the company has not been willing to address.  I am very disappointed that a food I recommended so highly in the past has had these problems.  I have changed my dogs to Eagle Pack Holistic Selects. It is more expensive, but they are back to their old selves-- healthy, no digestive troubles, and great coats.'

In [60]:
bag_of_words(texts)

{'s': 0,
 'o': 1,
 'm': 2,
 'e': 3,
 't': 4,
 'h': 5,
 'i': 6,
 'n': 7,
 'g': 8,
 'c': 9,
 'a': 10,
 'd': 11,
 'w': 12,
 'f': 13,
 'r': 14,
 'v': 15,
 'l': 16,
 'y': 17,
 'b': 18,
 '.': 19,
 ',': 20,
 '(': 21,
 '2': 22,
 '0': 23,
 '7': 24,
 ')': 25,
 'x': 26,
 'p': 27,
 'u': 28,
 'q': 29,
 'k': 30,
 '-': 31,
 '/': 32}

In [78]:
def load_words(file_name):   
    inFile = open(file_name, 'r')
    # wordlist: list of strings
    wordlist = []
    for line in inFile:
        wordlist.extend([word.lower() for word in line.split('\n')])
    wordlist = list(set(wordlist))
    wordlist.remove('')
    
    return wordlist

In [76]:
inFile = open('stopwords.txt', 'r')
# wordlist: list of strings
wordlist = []
for line in inFile:
    wordlist.extend([word.lower() for word in line.split('\n')])
wordlist = list(set(wordlist))
wordlist.remove('')

In [79]:
wordlist = load_words('stopwords.txt')
wordlist = list(set(wordlist))
wordlist

['had',
 'her',
 'a',
 'were',
 't',
 'will',
 'only',
 'here',
 'under',
 'of',
 'does',
 'has',
 'some',
 'over',
 'more',
 'because',
 'me',
 'them',
 'and',
 'is',
 'off',
 'than',
 'these',
 'into',
 'why',
 'do',
 'while',
 'by',
 'it',
 'nor',
 'its',
 'after',
 'both',
 'any',
 'there',
 'being',
 'have',
 'few',
 'same',
 'she',
 'was',
 'yourself',
 'yourselves',
 'during',
 'so',
 'most',
 'my',
 'but',
 'are',
 'against',
 'ours',
 'between',
 'should',
 'how',
 'at',
 'where',
 'hers',
 'each',
 'above',
 'with',
 'am',
 'herself',
 'our',
 'to',
 'very',
 'just',
 's',
 'now',
 'in',
 'once',
 'on',
 'the',
 'you',
 'having',
 'from',
 'ourselves',
 'who',
 'myself',
 'down',
 'then',
 'don',
 'him',
 'they',
 'through',
 'out',
 'further',
 'below',
 'own',
 'whom',
 'an',
 'i',
 'doing',
 'be',
 'about',
 'as',
 'until',
 'all',
 'which',
 'for',
 'theirs',
 'when',
 'such',
 'other',
 'their',
 'did',
 'we',
 'yours',
 'what',
 'this',
 'been',
 'can',
 'if',
 'himself

In [72]:
wordlist.remove('')

In [73]:
wordlist

['had',
 'her',
 'a',
 'were',
 't',
 'will',
 'only',
 'here',
 'under',
 'of',
 'does',
 'has',
 'some',
 'over',
 'more',
 'because',
 'me',
 'them',
 'and',
 'is',
 'off',
 'than',
 'these',
 'into',
 'why',
 'do',
 'while',
 'by',
 'it',
 'nor',
 'its',
 'after',
 'both',
 'any',
 'there',
 'being',
 'have',
 'few',
 'same',
 'she',
 'was',
 'yourself',
 'yourselves',
 'during',
 'so',
 'most',
 'my',
 'but',
 'are',
 'against',
 'ours',
 'between',
 'should',
 'how',
 'at',
 'where',
 'hers',
 'each',
 'above',
 'with',
 'am',
 'herself',
 'our',
 'to',
 'very',
 'just',
 's',
 'now',
 'in',
 'once',
 'on',
 'the',
 'you',
 'having',
 'from',
 'ourselves',
 'who',
 'myself',
 'down',
 'then',
 'don',
 'him',
 'they',
 'through',
 'out',
 'further',
 'below',
 'own',
 'whom',
 'an',
 'i',
 'doing',
 'be',
 'about',
 'as',
 'until',
 'all',
 'which',
 'for',
 'theirs',
 'when',
 'such',
 'other',
 'their',
 'did',
 'we',
 'yours',
 'what',
 'this',
 'been',
 'can',
 'if',
 'himself