In [1]:
import pandas as pd
import numpy as np
from scipy import stats as st
import math
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
pi = np.pi
e = np.e

In [3]:
n,d = 3,4
n,d

(3, 4)

In [5]:
[n,d] = 3,4
[n,d]

[3, 4]

In [6]:
X = np.array([[2,3,4],[4,5,6],[6,7,8],[8,9,0]])
X

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8],
       [8, 9, 0]])

In [16]:
np.linalg.norm(X, axis = 1)

array([ 5.38516481,  8.77496439, 12.20655562, 12.04159458])

In [15]:
x = X[:, np.newaxis]
x

array([[[2, 3, 4]],

       [[4, 5, 6]],

       [[6, 7, 8]],

       [[8, 9, 0]]])

In [13]:
np.linalg.norm(x, axis = 2)

array([[ 5.38516481],
       [ 8.77496439],
       [12.20655562],
       [12.04159458]])

In [14]:
np.linalg.norm(np.array([2,3,4]))

5.385164807134504

In [18]:
1e-3 ==0.001

True

In [19]:
x

array([[[2, 3, 4]],

       [[4, 5, 6]],

       [[6, 7, 8]],

       [[8, 9, 0]]])

In [20]:
X

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8],
       [8, 9, 0]])

In [23]:
s = np.where(X==2)
s

(array([0], dtype=int64), array([0], dtype=int64))

In [24]:
arr = np.array([[11, 12, 13],
                [14, 15, 16],
                [17, 15, 11],
                [12, 14, 15]])

In [27]:
result = np.where(arr == 15)
result[0][0]

1