In [1]:
import sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append("..")
from utils import *
from linear_regression import *
from svm import *
from softmax import *
from features import *
from kernel import *

In [20]:
n, d, k = 3, 5, 7
X = np.arange(0, n * d).reshape(n, d)
zeros = np.zeros((k, d))
temp = 0.2
theta = np.arange(0, k * d).reshape(k, d)

In [17]:
def compute_probabilities(X, theta, temp_parameter):
    """
    Computes, for each datapoint X[i], the probability that X[i] is labeled as j
    for j = 0, 1, ..., k-1

    Args:
        X - (n, d) NumPy array (n datapoints each with d features)
        theta - (k, d) NumPy array, where row j represents the parameters of our model for label j
        temp_parameter - the temperature parameter of softmax function (scalar)
    Returns:
        H - (k, n) NumPy array, where each entry H[j][i] is the probability that X[i] is labeled as j
    """
    #YOUR CODE HERE
    v = (theta @ X.T)/temp_parameter
    C = np.max(v, axis=0)
    exp = np.exp(v-C)
    sum = np.sum(exp, axis = 0)
    h = (1/sum)*exp


    return h

In [23]:
compute_probabilities(X, theta, temp) #== np.ones((k, n)) / k

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [7.12457641e-218, 0.00000000e+000, 0.00000000e+000],
       [2.66919022e-109, 0.00000000e+000, 0.00000000e+000],
       [1.00000000e+000, 1.00000000e+000, 1.00000000e+000]])

In [19]:
np.ones((k, n)) / k

array([[0.14285714, 0.14285714, 0.14285714],
       [0.14285714, 0.14285714, 0.14285714],
       [0.14285714, 0.14285714, 0.14285714],
       [0.14285714, 0.14285714, 0.14285714],
       [0.14285714, 0.14285714, 0.14285714],
       [0.14285714, 0.14285714, 0.14285714],
       [0.14285714, 0.14285714, 0.14285714]])

In [11]:
np.log(compute_probabilities(X, theta, temp))

<ipython-input-11-35899e7c0cf9>:1: RuntimeWarning: divide by zero encountered in log
  np.log(compute_probabilities(X, theta, temp))


array([[ -inf,  -inf,  -inf],
       [ -inf,  -inf,  -inf],
       [ -inf,  -inf,  -inf],
       [ -inf,  -inf,  -inf],
       [-500.,  -inf,  -inf],
       [-250.,  -inf,  -inf],
       [   0.,    0.,    0.]])

In [26]:
n, d, k = 3, 5, 7
X = np.arange(0, n * d).reshape(n, d)
Y = np.arange(0, n)
zeros = np.zeros((k, d))
temp = 0.2

lambda_factor = 0.5

In [27]:
def compute_cost_function(X, Y, theta, lambda_factor, temp_parameter):
    """
    Computes the total cost over every datapoint.

    Args:
        X - (n, d) NumPy array (n datapoints each with d features)
        Y - (n, ) NumPy array containing the labels (a number from 0-9) for each
            data point
        theta - (k, d) NumPy array, where row j represents the parameters of our
                model for label j
        lambda_factor - the regularization constant (scalar)
        temp_parameter - the temperature parameter of softmax function (scalar)

    Returns
        c - the cost value (scalar)
    """
    #YOUR CODE HERE
    n = X.shape[0]
    k = theta.shape[0]
    log = np.log(compute_probabilities(X, theta, temp_parameter))

    Loss = 0
    for i in range(n):
        for j in range(k):
            if Y[i] == j:
                Loss += Y[i]*log[j,i]

    J = (-1/n)*Loss + lambda_factor/2 * np.sum(theta**2)

    return J

In [28]:
np.log(compute_probabilities(X, theta, temp))

<ipython-input-28-35899e7c0cf9>:1: RuntimeWarning: divide by zero encountered in log
  np.log(compute_probabilities(X, theta, temp))


array([[ -inf,  -inf,  -inf],
       [ -inf,  -inf,  -inf],
       [ -inf,  -inf,  -inf],
       [ -inf,  -inf,  -inf],
       [-500.,  -inf,  -inf],
       [-250.,  -inf,  -inf],
       [   0.,    0.,    0.]])

In [29]:
compute_cost_function(X, Y, theta, lambda_factor, temp)

<ipython-input-27-485d2e17b30e>:20: RuntimeWarning: divide by zero encountered in log
  log = np.log(compute_probabilities(X, theta, temp_parameter))
<ipython-input-27-485d2e17b30e>:26: RuntimeWarning: invalid value encountered in multiply
  Loss += Y[i]*log[j,i]


nan